version: '3'
services:
  web:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
