const ANIMALS = [
    "Aardvark",
    "Albatross",
    "Alligator",
    "Alpaca",
    "Ant",
    "Anteater",
    "Antelope",
    "Armadillo",
    "Arowana",
    "Asp",
    "Ass",
    "Aye-aye",
    "Baboon",
    "Badger",
    "Baiji",
    "Balinese",
    "Basset Hound",
    "Bat",
    "Bear",
    "Beaver",
    "Beetle",
    "Binturong",
    "Bird",
    "Bison",
    "Black Marlin",
    "Black Rhinoceros",
    "Bloodhound",
    "Booby",
    "Booby Trap",
    "Bolognese Dog",
    "Bombay",
    "Bordeaux",
    "Bottlenose Dolphin",
    "Bowerbird",
    "Boxer Dog",
    "Boykin Spaniel",
    "Budgerigar",
    "Buffalo",
    "Bull",
    "Bulldog",
    "Bullfrog",
    "Bumblebee",
    "Burbot",
    "Burro",
    "Caiman",
    "Cairn Terrier",
    "Camel",
    "Capybara",
    "Caracal",
    "Cassowary",
    "Cat",
    "Caterpillar",
    "Cattle",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Chipmunk",
    "Cichlid",
    "Cobra",
    "Cockroach",
    "Cod",
    "Collie",
    "Cormorant",
    "Coyote",
    "Crab",
    "Crane",
    "Crocodile",
    "Crow",
    "Cuckoo",
    "Curlew",
    "Cuttlefish",
    "Dachshund",
    "Dalmatian",
    "Dama Gazelle",
    "Dandie Dinmont Terrier",
    "Deer",
    "Dhole",
    "Dingo",
    "Dinosaur",
    "Dog",
    "Dolphin",
    "Donkey",
    "Dragonfly",
    "Duck",
    "Dumpling Squid",
    "Eagle",
    "Earthworm",
    "East African Oryx",
    "Echidna",
    "Eel",
    "Egret",
    "Elephant",
    "Elephant Seal",
    "Elk",
    "Emu",
    "Endangered Species",
    "English Bulldog",
    "English Springer Spaniel",
    "Erdman",
    "Ermine",
    "Eskimo Dog",
    "Fairy Penguin",
    "Ferret",
    "Finch",
    "Fish",
    "Flamingo",
    "Flea",
    "Fly",
    "Flying Squirrel",
    "Fox",
    "French Bulldog",
    "Galah",
    "Galápagos Tortoise",
    "Gannet",
    "Gecko",
    "Gerbil",
    "Giant Panda",
    "Gibbon",
    "Gila Monster",
    "Goat",
    "Goldfish",
    "Goose",
    "Gorilla",
    "Great Dane",
    "Greater Swiss Mountain Dog",
    "Green Sea Turtle",
    "Greyhound",
    "Grizzly Bear",
    "Groundhog",
    "Guinea Pig",
    "Haddock",
    "Hagfish",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Herring",
    "Himalayan",
    "Hippopotamus",
    "Horse",
    "Housefly",
    "Human",
    "Hummingbird",
    "Husky",
    "Ibex",
    "Iguana",
    "Impala",
    "Indian Elephant",
    "Indian Star Tortoise",
    "Indigo Bunting",
    "Indri",
    "Iriomote Cat",
    "Jackal",
    "Jaguar",
    "Javan Rhino",
    "Jellyfish",
    "Kangaroo",
    "King Cobra",
    "Kingfisher",
    "Kinkajou",
    "Koala",
    "Komodo Dragon",
    "Kookaburra",
    "Kouprey",
    "Kudu"
];

export default ANIMALS